### ISSUE TITLE
Problem Building

### ISSUE THREAD

**Issue by ZachEngr** [whiteout-io/mail-html5#248]
Hi,

I followed the instructions in the readme file for building and installed the required components. I'm getting a build error that I've been unable to resolve the past few days and I have a feeling it is something I've done incorrectly in my install. I'm running Win8.1. Here's the output from the cmd shell:

![output](https://cloud.githubusercontent.com/assets/10413766/5734864/26e3ceaa-9b82-11e4-8e16-45428d3f25df.jpg)

Any idea what I've done wrong?

Thanks,
Zach

**Comment by felixhammerl** [comment]
i don't think there's anything you've done wrong. i guess what you're seeing stems from the fact that you're using windows. it fails on [this line](https://github.com/whiteout-io/mail-html5/blob/master/Gruntfile.js#L27), which executes a shell script, which probably doesn't work on windows machines.

**Comment by ZachEngr** [comment]
Thanks for the advice. I'll try that. I do have a Linux boot, though I typically work in Windows. Would you expect a Linux VM in Windows to work OK?

Thanks again,
Zach

**Comment by felixhammerl** [comment]
https://github.com/whiteout-io/mail-html5/issues/222

you might find this helpful on linux :)
