### ISSUE TITLE
How to use whiteout under apache?

### ISSUE THREAD

**Issue by xokvictor** [whiteout-io/mail-html5#264]
Hi, help me please!

i do next steps:
1) Download https://github.com/whiteout-io/mail-html5/releases/download/v0.22.1/whiteout-mail_0.22.1.zip
2) Upload it to Apache virtualhost DocumentRoot ("whiteout.local", for example)
3) Go to http://whiteout.local and try connect my mail account.
4) Then I put my login, password and settings and see this:
Connection Error
Runtime does not offer TCPSockets!

When i run whiteout under node.js server in development mode all worked fine and I enter to my mailbox.

How run whiteout under Apache?

**Comment by tanx** [comment]
We do not support apache. A node server is required to proxy tcp connections via socket.io. See Readme: 

https://github.com/whiteout-io/mail-html5#deploying-web-app--selfhosting
