### ISSUE TITLE
Can't retrieve TOKEN at webmail if signing into "@wmail.io" account

### ISSUE THREAD

**Issue by erreip** [whiteout-io/mail-html5#265]
I'm signing into whiteout.io using a "@wmail.io" account. It entered the email and passcode which then takes me to the screen where it requests a 'TOKEN' or basically a 2FA but, that TOKEN is sent to the email one is signing into. 
This is only an issue for me when I'm signing into a "@wmail.io" account because when using an existing email (e.g. "@gmail.") I can simply log into THAT account and get the TOKEN.

Am I missing something?

Please advise.

**Comment by felixhammerl** [comment]
yes, this is still an open issue, but it will soon be obsoleted when we change the way key sync works. in the meantime: you can sign into that wmail.io account with another IMAP client, e.g. Apple Mail or Thunderbird, to retrieve the token. it will be readable in plain text

**Comment by erreip** [comment]
Got it!
Thanks for the response. Oh and FYI, I opted to import the keypair manually and that worked without having to go to a another IMAP client.
