### ISSUE TITLE
Please fill out all required fields! Error with importing key

### ISSUE THREAD

**Issue by greggpeacock** [whiteout-io/mail-html5#268]
https://mail.whiteout.io/#/login-new-device

I've also tried this on the Android app and receive the same error. I can select any valid or invalid file, enter in a correct or incorrect passphrase associated with that file and regardless, I always get this error. It appears that this is a form-validation issue as the response is immediate.

![image](https://cloud.githubusercontent.com/assets/7033875/6134094/a1d6c9e0-b113-11e4-8557-3075c8d7c5d3.png)

**Comment by blacknred0** [comment]
+1 - I also get the same error.

**Comment by felixhammerl** [comment]
Cannot reproduce.... are you sure the key is readable? Here are the relevant chunks of code:

https://github.com/whiteout-io/mail-html5/blob/master/src/js/directive/login-new-device.js
https://github.com/whiteout-io/mail-html5/blob/master/src/js/controller/login/login-new-device.js#L9L12

Are you SURE that the key contains BOTH the private and the public key?

**Comment by blacknred0** [comment]
After reading your message and the relevant chunks of code, I can confirm that this was an end-user error from my side.  It wasn't obvious to me that I needed to import both private and public keys at the same time.  Perhaps for future new users like me, a little bur to remind us to have both (private and public) keys on the same file prior of importing it to the software wouldn't hurt.

Thanks for the feedback.

**Comment by tanx** [comment]
It work too if you only import the private key file and that file contains both the private AND public key. But the app needs needs both in any case.
