### ISSUE TITLE
How to login to mail if i don't export private key before?

### ISSUE THREAD

**Issue by xokvictor** [whiteout-io/mail-html5#271]
At first time i have generated private key and then logout from mail in browser at another laptop.
When i tried login into mail account on my laptop, i see page "import PGP key".
Then i go to https://whiteout.io/revocation.html and enter my mail, then i see message "Your account has been prepared for reset. We've sent you an email with further steps. Please check your inbox."
But i can't login at this mail, because i haven't private key for login.

How to login?

**Comment by tanx** [comment]
This is a UX issue we are aware of and will address soon.
