### ISSUE TITLE
Support SMTP/IMAP over SSH tunnel

### ISSUE THREAD

**Issue by singpolyma** [whiteout-io/mail-html5#277]
Instead of using the hacky SMTPAUTH situation, some of my mailservers are configured to only accept mail locally and then mail can be sent over an SSH tunnel (this also allows for authentication using revokable keys, instead of a single password).  This is easy to do from my own computers, but is more complicated from a mobile/web setup.  It would be nice if clients like whiteout could support SSH tunnelling as an alternative to TLS.

**Comment by tanx** [comment]
Not sure if this is a common use case. Right now we're focusing on implementing broad standards.

**Comment by singpolyma** [comment]
@tanx would a pull request implementing this functionality be accepted?

**Comment by tanx** [comment]
Probably not. Keeping a codebase lean and simple is the best way to minimize bugs :)

**Comment by tanx** [comment]
If you want to test this in your own branch though forge seems to support ssh. So it should not be too much work:

https://github.com/digitalbazaar/forge/blob/master/README.md#ssh

If others ask for this feature we might consider accepting a PR later.
