### ISSUE TITLE
Where is Starred folder?

### ISSUE THREAD

**Issue by xokvictor** [whiteout-io/mail-html5#280]
I can starred my messages but can't filtered by starred. Why?

**Comment by tanx** [comment]
If you're using gmail it should be on the left.

![bildschirmfoto 2015-02-16 um 11 47 05](https://cloud.githubusercontent.com/assets/1374174/6210599/924b384a-b5d1-11e4-945b-214862923530.png)

**Comment by rockman73** [comment]
Not everyone uses GMail. ;)

Please reconsider a virtual folder to show starred/flagged email as a new feature request.
