### ISSUE TITLE
Android: Error: Socket timed out

### ISSUE THREAD

**Issue by PiNotEqual3** [whiteout-io/mail-html5#302]
In the android app I always get "Socket timed out!" error and no new mails are shown only old ones from first sync. After this message the app hangs for a while until it finally crashs. After restart it takes a few seconds then it does the same. I already cleared app cache but no luck with that.

Android 4.4.4 (CyanogenMod 11).

What I did: Installed the app. Logged in with google oauth. Created a key. wrote a short message with an image attached. The message is still in outbox. If I open the mail it shows no content only controls but I can't delete it.

Also I can't export my private key.

**Comment by felixhammerl** [comment]
hi! 
we're not officially supporting cyanogenmod.
key export uses the same download mechanism, which has issues in the setup we're using. sorry about that :(
the key export issue will soon be obsoleted by our new key sync mechanism. please try generating/exporting your key on the desktop, you'll be able to export it there.

**Comment by PiNotEqual3** [comment]
After all I think this is related to #304 Lazy load message list
