### ISSUE TITLE
Lazy load message list

### ISSUE THREAD

**Issue by PiNotEqual3** [whiteout-io/mail-html5#304]
I logged in and it shows me an empty inbox.

In F12 log I can see a lot of actions. I am guessing it is downloading all mails from my inbox?

I got ~20'000 Mails there. That's gone be fun...

(Chrome Browser)

**Comment by PiNotEqual3** [comment]
If I block mailbox access (see #305) I can view inbox with cached messages. I am sure I don't want to keep all mails in browser cache...

**Comment by felixhammerl** [comment]
the messages are kept safely inside your browser's indexeddb, and you want them there so you can use whiteout mail offline.

but yes, eager loading is a performance bottleneck and we're addressing that as we speak. will probably switch to lazy loading messages in the near future.

**Comment by felixhammerl** [comment]
this has been addressen a couple of releases ago.
