### ISSUE TITLE
Mail password is stored in app-config

### ISSUE THREAD

**Issue by PiNotEqual3** [whiteout-io/mail-html5#306]
Looks like my mail password is stored in IndexedDB app-config.

It is encrypted by a PGP key but that key is probably also readable. I think storing the password should be optional.

**Comment by felixhammerl** [comment]
yeah, as an imap app, we kind of need your password to log into imap ... your password is on your local machine and not upload to weird places, so no need to be concerned :)

**Comment by PiNotEqual3** [comment]
I think it is a security issue if the password is stored in the browser. Anyone with read access to local files or backup could steal the password. There have already been issue where browser cache was readable from remote. Also other local users could get access.

For the IMAP client is enough to have the password in the session.

It should be optional to store the password permanent.

**Comment by felixhammerl** [comment]
no, this is not a security issue. think about setting up thunderbird. or mail.app. where do you think you password is stored? answer: your password is stored on your machine :)

the fact that we happen to use a browser makes no difference here. 

and no, we *need* to store the password, think about people assigning app-specific passwords on gmail. that is exactly what passwords were made for.

what you're referring to is oauth.

**Comment by PiNotEqual3** [comment]
So if I am on a public computer e.g. in university or an internet café, start the web app, check my mails it is no security concern that my password is permanently stored accessible to everyone how walks by?

**Comment by felixhammerl** [comment]
what you're talking about is **endpoint security**, which is out of scope for this app.

i am rather surprised that the password is what got your attention, not the fact that you are using your **private key** on an **untrusted machine** ;)
