### ISSUE TITLE
Plaintext email links starting with "<" and ip instead of www not recognized 

### ISSUE THREAD

**Issue by zishor** [whiteout-io/mail-html5#307]
Awesome project guys, really liking it!

Just a small thing with the parsing of http(s) links in plaintext emails:

Bitbucket sends build confirmation emails with links starting with an "<" and ending with ">":

See "<" http://134.119.9.2.1:8080/job/XXXXX%20Commitbuild/386/ ">"

the preview here is filtering the <> stuff so I put in quotes.

The regex in read-sandbox.js (Line 183) is not liking it.

**Comment by ngzhian** [comment]
The regex currently used is:
```
(http(s)?:\/\/.)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)
```

quick search turned out [another regex](https://gist.github.com/gruber/249502) we can use:

copied here for ref:
```
\b((?:[a-z][\w\-]+:(?:\/{1,3}|[a-z0-9%])|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}\/)(?:[^\s()<>]|\((?:[^\s()<>]|(?:\([^\s()<>]+\)))*\))+(?:\((?:[^\s()<>]|(?:\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,<>?«»“”‘’]))
```

**Comment by zishor** [comment]
Thanks ngzhian. I never contributed so please excuse if I miss anything. 

What actually worked for me was splitting the two regexes like: 
```
lines[i] = lines[i].replace(/[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)/g,createArchor);
lines[i] = lines[i].replace(/(https?:\/\/[^\s]+)/g,createArchor);
```

Would this be worth creating a branch and making a pull request?

**Comment by felixhammerl** [comment]
is `<hyperlink>` convention like `/emphasized/`, `_underlined_`, and `*bold*` i am not aware of?
