### ISSUE TITLE
Email content field missing in »New email« dialog (Android)

### ISSUE THREAD

**Issue by jancborchardt** [whiteout-io/mail-html5#312]
Using the »New email« dialog from the current Android app, the content field doesn’t show up. That can’t be right, eh? ;)

![screenshot_2015-03-07-11-43-15](https://cloud.githubusercontent.com/assets/925062/6541104/0c39e834-c4c0-11e4-8c61-a1903f980522.png)

Version 0.24.2, Android 5.0.1 on a Nexus 4. Let me know how I can help debug.

**Comment by felixhammerl** [comment]
click below the subject, but yeah we should put a placeholder there...

**Comment by jancborchardt** [comment]
Hehe – there you have it. ;) Yes, a placeholder is needed there.

Also it’s a bit strange generally that sometimes text fields have boxes around them (subject, search) and sometimes not (recipient, message body). But probably the placeholder there will already take care of the problem, I’m also not too fond of putting more boxes there.

**Comment by jancborchardt** [comment]
![](http://blakesnow.com/wp-content/uploads/sites/2/2015/05/thumbs-up-gif.gif)

**Comment by felixhammerl** [comment]
![](http://i3.kym-cdn.com/entries/icons/square/000/013/974/clap.gif)
