### ISSUE TITLE
Use only specific hosts

### ISSUE THREAD

**Issue by JHGitty** [whiteout-io/mail-html5#340]
Is there any way to allow only special hosts? Let's say I only want to allow logins to @example.com email adresses.

**Comment by felixhammerl** [comment]
no, this doesn't make sense for PGP client built specifically with general-purpose IMAP connectivity in mind.

**Comment by JHGitty** [comment]
This would be needed for integration in company networks because IT admins and the administration of the companies often only want that the users only can check the company emails.

**Comment by felixhammerl** [comment]
how would you wanna deploy it? as a webapp? in that case, your best shot would be checking the hosts [here](https://github.com/whiteout-io/mail-html5/blob/master/server.js#L126), pretty much the same way I check the ports...
