### ISSUE TITLE
Archive button like Gmail

### ISSUE THREAD

**Issue by mrbiber** [whiteout-io/mail-html5#342]
Rather than having to manually archive messages to an archive folder, it would be great to have an "Archive" button like gmail has it.

**Comment by felixhammerl** [comment]
sorry, but archive is gmail-specific, not standard to imap.

**Comment by mrbiber** [comment]
Thanks for replying so quickly. I should have been more explicit: On non-Gmail IMAP servers, the folder to archive to could either be manually configured or created by the client. Thunderbird does this as well for arbitrary servers.

**Comment by felixhammerl** [comment]
if we did this, it would only make sense for gmail, b/c archive functionality is only useful if you have this default sinkhole where all your messages are kept automagically, which is server-side functionality. Thunderbird's stuff makes no sense whatsoever b/c they just create another folder, albeit with a speed-dial button "move this email to another folder in whichever way you see fit".

**Comment by mrbiber** [comment]
Yes exactly, making sense or not, I find this feature in Thunderbird incredibly useful. But I see that I'm not convincing anyone here :-)
