### ISSUE TITLE
Key verification responds with an error

### ISSUE THREAD

**Issue by majnu-campact** [whiteout-io/mail-html5#355]
I just signed up and after clicking the verfication link in my Email I got
{"error":"Invalid request!"}
The app does seem to work though. Just the feedback is confusing.

**Comment by majnu-campact** [comment]
It seems like I can't send out mails. There is also no Outbox where I could see the unsent mails. Is that related to the above issue? 
I am guessing that my public key wasn't verified. When I pasted the key in the subscription process, I only pasted the private part. Could that be the reason?

**Comment by felixhammerl** [comment]
normally, the client handles the verification on its own. if you're in the main application screen with the mail list, your verifciation did already go through.

the outbox is only shown if there's actually mails in the outbox :)
