### ISSUE TITLE
Export decrypted, plain-text email to offline local storage

### ISSUE THREAD

**Issue by rockman73** [whiteout-io/mail-html5#358]
Guys, first of all, great work on Whiteout Mail! Love the it so far. 

I have a new feature request:

John uses Whiteout Mail Client. He prefers to download and archive email offline, then delete from the cloud. John is required to save the decrypted email onto the local system drive as a plain-text EML or MSG file, either one at a time or selected emails within the Whiteout Mail Client. There should be a conspicuous, visual indicator when viewing the encrypted email within the Whiteout Mail Client indicating the plain-text version of the email was saved offline on the datetime. John then securely archives the offline, plain-text email files elsewhere.

I hope this makes sense?

Cheers
\m/

**Comment by felixhammerl** [comment]
This idea is totaly valid, I've seen people do that. But in that case, a lightweight PGP solution like Whiteout Mail is probably not your tool of choice. I guess you would rather do that with a shell script and GPG, or GPGTools. Last time we talked to the GPGTools guys, they had a feature called "permanent decryption" on their roadmap. Though I'm not sure how far along that is.
http://support.gpgtools.org/discussions/feedback/1249-permanent-decryption

**Comment by rockman73** [comment]
Thx for the suggestion, but I use Microsoft Windows.
