### ISSUE TITLE
Account passphrase set, but not prompted anomaly

### ISSUE THREAD

**Issue by rockman73** [whiteout-io/mail-html5#360]
I experienced an anomaly. The Whiteout Mail client did not ask me for the account passphrase. After scratching my head and thinking some more, I am sure that I did set one up according to my password manager. So, I reset the passphrase, then closed the app. When I re-opened the app, it hung. I closed the app again, then re-opened it. I get the passphrase prompt now. 

Unfortunately, I have not yet been able to repro this bug, but will post details when I have them. This is on Windows 7 64-bit and Whiteout Mail 1.0.1 Chrome app.

**Comment by felixhammerl** [comment]
alright, we'll have a look out for this bug, but since this is a single event, i'll close this for now.

**Comment by rockman73** [comment]
Hello, I noticed this occurred again when I recently upgraded to v1.1.0 of the Chrome app. Can you reproduce this behavior?
