### ISSUE TITLE
Accessibility: Whiteout Mail Client UI needs higher contrast theme and Zoom

### ISSUE THREAD

**Issue by rockman73** [whiteout-io/mail-html5#362]
Whiteout Mail Client UI needs higher contrast theme, or selectable themes to improve accessibility. A zoom function should also help accessibility.

**Comment by nilsws** [comment]
Agree about the contrast. The light blue coloring isn't very eye-friendly. A couple color themes as options would be great.

**Comment by rockman73** [comment]
Won't fix?

**Comment by felixhammerl** [comment]
the stylesheet was created with a complete design language in mind. changing that would likely end up in a major design rework, for which we don't have the resources. this will not be fixed from our side, sorry.
