### ISSUE TITLE
Back navigation key / mouse wheel left not working in chrome app

### ISSUE THREAD

**Issue by DejayRezme** [whiteout-io/mail-html5#365]
When I click on a mail I would like to use the navigate back key to get back to the email list. I'm so used to the mouse wheel left tilt which triggers the "navigate back" key in the browser. I guess on android app this should work with the "back" key or with swipe right.

**Comment by felixhammerl** [comment]
mouse wheel tilt is not a universally recognized gesture for "back" across manufacturers or OSes, unlike backspace.

**Comment by DejayRezme** [comment]
I realize this is a feature request but just to add some thoughts :)

Afaik the mouse wheel tilt key simply triggers a windows keycode or event (or maybe USB keycode?) for "navigate back" that you can also find as a physical key on keyboards or mobile phones (I think on iphone and some android phones it's not a physical key but an OS key). So it's not about my mouse wheel tilt but the "navigate back event". Not sure if / where this is defined but all browsers react to it (just like they do to Alt-Cursor Left / Right). This might even trigger the same action and event across mobile and windows when using the back key on smartphones / tablets. So it is a cross platform "metaphor" for backing out - actually similar to what the escape key does in menus hierarchies.
