### ISSUE TITLE
Import keypair gmail issue

### ISSUE THREAD

**Issue by tripplet** [whiteout-io/mail-html5#370]
Hi,

I wanted to import my pgp key but got the not so clear error message: User Id's don't match
The issue was that my pgp was issued to my mail adress without the "." inside it, which I mostly use.
But after the google OAuth process whiteout-io used my mail address with the dot inside.

It would be nice if you could ignore dots inside the check (for gmail) or somehow display the mismatched UserIds as this was not very clear and took some debugging to determine the issue.

Google's policy for gmail addresses as reference: http://gmailblog.blogspot.de/2008/03/2-hidden-ways-to-get-more-from-your.html

Thanks

**Comment by felixhammerl** [comment]
This is a very Gmail specific problem, which makes it a won't fix for us. The user id doesn't match, and that's that. However: Since you key pair was generated outside of Whiteout Mail anyway, why not add the proper user ID in GPG and try again?
