### ISSUE TITLE
Do not hide (ever) email address 

### ISSUE THREAD

**Issue by klaszlo** [whiteout-io/mail-html5#378]
I think when emailing, the first and most important information is the email address.

I just noticed that for some users there is no email address displayed, just his name.

Are we going the Microsoft Outlook way? I think it is *SILLY* to hide the email address.
I can not think at any situation where email address should be hidden. 
Please do not follow Google or Microsoft in this regard. It is especially confusing when a contact has multiple email address, or his name is a common name and I have multiple contact with same real name.

So please display email address at all times. Hide the name, if hiding is absolutely necessary...

**Comment by felixhammerl** [comment]
the email address is hidden on mobile/tablet to conserve screen real estate, but can be displayed by clicking the `^`

**Comment by klaszlo** [comment]
felixhammerl: 
Yes I tried it out on a android based mobile phone.

If you mean the ^/v character in the upper right corner, then it is really easy to miss, and hit on the white space above which redirects to the previous page (< Inbox in my example).
I think it should be improved. Especially the name is displayed as:
Michael ...

The '...' char is minuscule, and not clickable, although it is not evident. So if you try to hit on it, you most probably end up sending out an invitation.

Also it DOES NOT display the email address in all case. It is true, the 'From:' field works, and displayed the email address, but neither the 'To:' nor the 'Cc:' field is expanded to get the email address.
Clicking on either field also ends up sending an invitation, the 'To:' field even has an 'add to group' icon next to it. So sending out an invitation in that case looks counterintuitive.

I think it is still a valid bugreport.
