### ISSUE TITLE
integrate with OpenKeyChain for key management

### ISSUE THREAD

**Issue by pravi** [whiteout-io/mail-html5#380]
This would make key management easier for user and also would avoid duplication. So when choosing the key, the user should be given an option to use Open Key Chain.

**Comment by felixhammerl** [comment]
Patches welcome :)

**Comment by tanx** [comment]
The goal of whiteout is do things differently than all those other email client + plugin solutions out there by being an integrated solution. If you want to use open keychain please use a client that support it.
