### ISSUE TITLE
How i can get access to my wmail if I lose private key and backup code?

### ISSUE THREAD

**Issue by xokvictor** [whiteout-io/mail-html5#387]
When i entered login and password system ask me for private key or backup code. But i lose it all.

**Comment by moparisthebest** [comment]
Assuming it works like they say it does and all your mails are OpenPGP encrypted to your key, there *is* no way to get your old ones back, they are effectively gone.

You *should* be able to regenerate a new key and send/receive new emails though?

**Comment by tanx** [comment]
> Assuming it works like they say it does and all your mails are OpenPGP encrypted to your key, there is no way to get your old ones back, they are effectively gone.
> 
> You should be able to regenerate a new key and send/receive new emails though?

Yes. That's exactly how it works. You can reset your wmail password here: https://admin.whiteout.io
