### ISSUE TITLE
PGP Manifest Unsupported?

### ISSUE THREAD

**Issue by rockman73** [whiteout-io/mail-html5#393]
I've attempted to communicate with a Lavaboom user. We have successfully exchanged public keys, however, there are two issues:
1) Encrypted email received from Lavaboom to Whiteout Mail cannot be viewed because Whiteout mail does not support PGP manifest? This can be fixed by Whiteout Mail.
2) Encrypted mails sent to Lavaboom from Whiteout Mail cannot be read correctly. This can be fixed by Lavaboom.

**Comment by felixhammerl** [comment]
Apparently, [Lavaboom unilaterally introduced a new mail structure](https://github.com/lavab/pgp-manifest-go) based on Bjarnis proposal that does not comply to the PGP/MIME specification. Lavaboom needs to fix this, since no other mailer out there is able to read this, either.

**Comment by rockman73** [comment]
Thank you for the quick response. Your explanation was helpful.
