### ISSUE TITLE
What i can do if i lost my private key?

### ISSUE THREAD

**Issue by xokvictor** [whiteout-io/mail-html5#396]
I can't access to my mail

**Comment by felixhammerl** [comment]
1) if you still have the backup code, you can recover.
2) if you still any working copy of whiteout mail with your key in it, you can recover.
3) if you have lost everything, you're host. such is the nature of pgp :(

Is it 1), 2), or 3)?

**Comment by xokvictor** [comment]
3)

Can you reset my account?

**Comment by felixhammerl** [comment]
1. Go to https://whiteout.io/revocation.html and revoke your public key on our key servers
2. Confirm deletion of public key
3. Log out of Whiteout Mail (if necessary)
4. Fire up Whiteout Mail, enter eMail address and click "Connect"

**Comment by xokvictor** [comment]
But I can't confirm deletion of public key, because this message go on my mail what i can't login.

**Comment by felixhammerl** [comment]
ok, plz tell me your wmail address

**Comment by xokvictor** [comment]
xok@wmail.io

**Comment by felixhammerl** [comment]
done. plz go straight to step 4.

**Comment by xokvictor** [comment]
Work! Many thx!
