### ISSUE TITLE
Something wrong when using whiteout

### ISSUE THREAD

**Issue by b-deng** [whiteout-io/mail-html5#399]
![image](https://cloud.githubusercontent.com/assets/10510806/9241634/85a5b968-41a8-11e5-81ae-cdecdf94d2b8.png)
Hi,everyone.I'm new to whiteout.As the picture shows,how can I resolve this problem?Another question,when logging,I need to input the backup code or upload the PGP key file,can I skip this step?I mean is there a method that I only input the email address and password then I can login successfully?
Thanks.

**Comment by felixhammerl** [comment]
do you know which imap server you are on? #394 should fix this
