### ISSUE TITLE
How to get out?

### ISSUE THREAD

**Issue by chew-z** [whiteout-io/mail-html5#400]
So I am no expert here but seems like my Whiteout stoped working long time ago. It always shows 'offline mode' and hangs downloading my Inbox forever. Good.

I have removed the app from my iPhone some time ago. But I could still access Whiteout Mail from Safari and it seems Whiteout imported a content of my gmail mailbox. I have searched for an option to remove the account and revoke access to my gamil account, went through FAQ etc. but no luck. I have tried emailing support but the mail gets stuck in Outbox.

So I am a bit lost here and my question is - How can I remove Whiteout account completely and revoke access to my gmail? How can I make sure it is realy wiped out?

<img width="190" alt="screen shot 2015-08-21 at 08 50 35" src="https://cloud.githubusercontent.com/assets/2264679/9402857/c355f6d0-47e1-11e5-917f-386ef6123a28.png">
<img width="586" alt="screen shot 2015-08-21 at 08 50 24" src="https://cloud.githubusercontent.com/assets/2264679/9402860/c53eacbc-47e1-11e5-9fe7-73e7dc76d870.png">

**Comment by felixhammerl** [comment]
Wipeout Whiteout? :(
Think of Whiteout Mail like Mozilla Thunderbird or Mail.app. Everything you do happened on your local machine, nothing stored on our servers -- apart from the public key of course. That means if you delete Whiteout Mail, you're done. If you wanna remove the public key, go [here](https://whiteout.io/revocation.html). If you wanna keep your PGP key, go to Account > Export keypair.
