### ISSUE TITLE
Threading

### ISSUE THREAD

**Issue by marcus433** [whiteout-io/mail-html5#92]
Your guys' libraries have helped me so much, trying to give back! Heres the source for a threading algorithm I've been working on hopefully it is useful for Whiteout! https://github.com/marcus433/Dropmail-Threading-Experimental/

**Comment by mcolyer** [comment]
@felixhammerl any update for when this might come?

**Comment by marcus433** [comment]
I built a threading algorithm that handles all cases quite fast if you guys are interested I'd be happy to share it



—

**Comment by felixhammerl** [comment]
No ETA yet, I'm afraid. The code is pretty simple, a UI across three device types is quite a bit more work. We're having other priorities right now, so it might be a while. Sorry :(
